package smarter.uearn.money.utils;

public class CountryCodes {

    private String[][] countryDetails = {
            {"India", "IN", "91"},
            {"Canada ", "CA", "1"},
            {"United Kingdom", "GB", "44"},
            {"United States", "US", "1"},
            {"Afghanistan", "AF", "93"},
            {"Albania", "AL", "355"},
            {"Algeria", "DZ", "213"},
            {"American Samoa", "AS", "1684"},
            {"Andorra", "AD", "376"},
            {"Angola", "AO", "244"},
            {"Anguilla", "AI", "1264"},
            {"Antarctica", "AQ", "672"},
            {"Antigua and Barbuda", "AG", "1268"},
            {"Argentina", "AR", "54"},
            {"Armenia", "AM", "374"},
            {"Aruba", "AW", "297"},
            {"Australia", "AU", "61"},
            {"Austria", "AT", "43"},
            {"Azerbaijan", "AZ", "994"},
            {"Bahamas", "BS", "1242"},
            {"Bahrain", "BH", "973"},
            {"Bangladesh", "BD", "880"},
            {"Barbados", "BB", "1246"},
            {"Belarus", "BY", "375"},
            {"Belgium", "BE", "32"},
            {"Belize", "BZ", "501"},
            {"Benin", "BJ", "229"},
            {"Bermuda", "BM", "1441"},
            {"Bhutan", "BT", "975"},
            {"Bolivia", "BO", "591"},
            {"Bosnia and Herzegovina", "BA", "387"},
            {"Botswana", "BW", "267"},
            {"Brazil", "BR", "55"},
            {"British Virgin Islands", "VG", "1284"},
            {"Brunei", "BN", "673"},
            {"Bulgaria", "BG", "359"},
            {"Burkina Faso", "BF", "226"},
            {"Burma (Myanmar)", "MM", "95"},
            {"Burundi", "BI", "257"},
            {"Cambodia", "KH", "855"},
            {"Cameroon", "CM", "237"},
            {"Canada", "CA", "1"},
            {"Cape Verde", "CV", "238"},
            {"Cayman Islands", "KY", "1345"},
            {"Central African Republic", "CF", "236"},
            {"Chad", "TD", "235"},
            {"Chile", "CL", "56"},
            {"China", "CN", "86"},
            {"Christmas Island", "CX", "61"},
            {"Cocos (Keeling) Islands", "CC", "61"},
            {"Colombia", "CO", "57"},
            {"Comoros", "KM", "269"},
            {"Cook Islands", "CK", "682"},
            {"Costa Rica", "CR", "506"},
            {"Croatia", "HR", "385"},
            {"Cuba", "CU", "53"},
            {"Cyprus", "CY", "357"},
            {"Czech Republic", "CZ", "420"},
            {"Democratic Republic of the Congo", "CD", "243"},
            {"Denmark", "DK", "45"},
            {"Djibouti", "DJ", "253"},
            {"Dominica", "DM", ""},
            {"Dominican Republic", "DO", "1809"},
            {"Ecuador", "EC", "593"},
            {"Egypt", "EY", "20"},
            {"El Salvador", "SV", "503"},
            {"Equatorial Guinea", "GQ", "240"},
            {"Eritrea", "ER", "291"},
            {"Estonia", "EE", "372"},
            {"Ethiopia", "ET", "251"},
            {"Falkland Islands", "FK", "500"},
            {"Faroe Islands", "FO", "298"},
            {"Fiji", "FJ", "679"},
            {"Finland", "FI", "358"},
            {"France", "FR", "33"},
            {"French Polynesia", "PF", "689"},
            {"Gabon", "GA", "241"},
            {"Gambia", "GM", "220"},
            {"Georgia", "GE", "995"},
            {"Germany", "DE", "49"},
            {"Ghana", "GH", "233"},
            {"Gibraltar", "GI", "350"},
            {"Greece", "GR", "30"},
            {"Greenland", "GL", "229"},
            {"Grenada", "GD", "1473"},
            {"Guam", "GU", "1671"},
            {"Guatemala", "GT", "502"},
            {"Guinea", "GN", "224"},
            {"Guinea-Bissau", "GW", "245"},
            {"Guyana", "GY", "592"},
            {"Haiti", "HT", "509"},
            {"Holy See (Vatican City)", "VA", "39"},
            {"Honduras", "HN", "504"},
            {"Hong Kong", "HK", "852"},
            {"Hungary", "HU", "36"},
            {"Iceland", "IS", "354"},
            {"India", "India", "91"},
            {"Indonesia", "ID", "62"},
            {"Iran", "IR", "98"},
            {"Iraq", "IQ", "964"},
            {"Ireland", "IE", "353"},
            {"Isle of Man", "IM", "44"},
            {"Israel", "IL", "972"},
            {"Italy", "IT", "39"},
            {"Ivory Coast", "CI", "225"},
            {"Jamaica", "JM", "1876"},
            {"Japan", "JP", "81"},
            {"Jordan", "JO", "962"},
            {"Kazakhstan", "KZ", "7"},
            {"Kenya", "KE", "254"},
            {"Kiribati", "KI", "686"},
            {"Kuwait", "KW", "965"},
            {"Kyrgyzstan", "KG", "996"},
            {"Laos", "LA", "856"},
            {"Latvia", "LV", "371"},
            {"Lebanon", "LB", "961"},
            {"Lesotho", "LS", "266"},
            {"Liberia", "LR", "231"},
            {"Libya", "LY", "218"},
            {"Liechtenstein", "LI", "423"},
            {"Lithuania", "LT", "370"},
            {"Luxembourg", "LU", "352"},
            {"Macau", "MO", "853"},
            {"Macedonia", "MK", "389"},
            {"Madagascar", "MG", "261"},
            {"Malawi", "MW", "265"},
            {"Malaysia", "MY", "60"},
            {"Maldives", "MV", "960"},
            {"Mali", "ML", "223"},
            {"Malta", "MT", "356"},
            {"Marshall Islands", "MH", "692"},
            {"Mauritania", "MR", "222"},
            {"Mauritius", "MU", "230"},
            {"Mayotte", "YT", "262"},
            {"Mexico", "MX", "52"},
            {"Micronesia", "FM", "691"},
            {"Moldova", "MD", "373"},
            {"Monaco", "MC", "377"},
            {"Mongolia", "MN", "976"},
            {"Montenegro", "ME", "382"},
            {"Montserrat", "MS", "1664"},
            {"Morocco", "MA", "212"},
            {"Mozambique", "MZ", "258"},
            {"Namibia", "NA", "264"},
            {"Nauru", "NR", "674"},
            {"Nepal", "NP", "977"},
            {"Netherlands", "NL", "31"},
            {"Netherlands Antilles", "AN", "599"},
            {"New Caledonia", "NC", "687"},
            {"New Zealand", "NZ", "64"},
            {"Nicaragua", "NI", "505"},
            {"Niger", "NE", "227"},
            {"Nigeria", "NG", "234"},
            {"Niue", "NU", "683"},
            {"Norfolk Island", "NFK", "672"},
            {"North Korea", "KP", "850"},
            {"Northern Mariana Islands", "MP", "1670"},
            {"Norway", "NO", "47"},
            {"Oman", "OM", "968"},
            {"Pakistan", "PK", "92"},
            {"Palau", "PW", "680"},
            {"Panama", "PA", "507"},
            {"Papua New Guinea", "PG", "675"},
            {"Paraguay", "PY", "595"},
            {"Peru", "PE", "51"},
            {"Philippines", "PH", "63"},
            {"Pitcairn Islands", "PN", "870"},
            {"Poland", "PL", "48"},
            {"Portugal", "PT", "351"},
            {"Puerto Rico", "PR", "1"},
            {"Qatar", "QA", "974"},
            {"Republic of the Congo", "CG", "242"},
            {"Romania", "RO", "40"},
            {"Russia", "RU", "7"},
            {"Rwanda", "RW", "250"},
            {"Saint Barthelemy", "BL", "590"},
            {"Saint Helena", "SH", "290"},
            {"Saint Kitts and Nevis", "KN", "1869"},
            {"Saint Lucia", "LC", "1758"},
            {"Saint Martin", "MF", "1599"},
            {"Saint Pierre and Miquelon", "PM", "508"},
            {"Saint Vincent and the Grenadines", "VC", "1784"},
            {"Samoa", "WS", "685"},
            {"San Marino", "SM", "378"},
            {"Sao Tome and Principe", "ST", "239"},
            {"Saudi Arabia", "SA", "966"},
            {"Senegal", "SN", "221"},
            {"Serbia", "RS", "381"},
            {"Seychelles", "SC", "248"},
            {"Sierra Leone", "SL", "232"},
            {"Singapore", "SG", "65"},
            {"Slovakia", "SK", "421"},
            {"Slovenia", "SI", "386"},
            {"Solomon Islands", "SB", "677"},
            {"Somalia", "SO", "252"},
            {"South Africa", "ZA", "27"},
            {"South Korea", "KR", "82"},
            {"Spain", "ES", "34"},
            {"Sri Lanka", "LK", "94"},
            {"Sudan", "SD", "249"},
            {"Suriname", "SR", "597"},
            {"Swaziland", "SZ", "268"},
            {"Sweden", "SE", "46"},
            {"Switzerland", "CH", "41"},
            {"Syria", "SY", "963"},
            {"Taiwan", "TW", "886"},
            {"Tajikistan", "TJ", "992"},
            {"Tanzania", "TZ", "255"},
            {"Thailand", "TH", "66"},
            {"Timor-Leste", "TL", "670"},
            {"Togo", "TG", "228"},
            {"Tokelau", "TK", "690"},
            {"Tonga", "TO", "676"},
            {"Trinidad and Tobago", "TT", "1868"},
            {"Tunisia", "TN", "216"},
            {"Turkey", "TR", "90"},
            {"Turkmenistan", "TM", "993"},
            {"Turks and Caicos Islands", "TC", "1649"},
            {"Tuvalu", "TV", "688"},
            {"Uganda", "UG", "256"},
            {"Ukraine", "UA", "380"},
            {"United Arab Emirates", "AE", "971"},
            {"United Kingdom", "GB", "44"},
            {"United States", "US", "1"},
            {"Uruguay", "UY", "598"},
            {"US Virgin Islands", "VI", "1340"},
            {"Uzbekistan", "UZ", "998"},
            {"Vanuatu", "VU", "678"},
            {"Venezuela", "VE", "58"},
            {"Vietnam", "VN", "84"},
            {"Wallis and Futuna", "WF", "681"},
            {"Yemen", "YE", "967"},
            {"Zambia", "ZM", "260"},
            {"Zimbabwe", "ZW", "263"}

    };

    private String[][] countryCurrency = {
            {"India", "INR"},
            {"Afganistan", "AFN"},
            {"Albania", "ALL"},
            {"Algeria", "DZD"},
            {"American", "USD"},
            {"Andorra", "EUR"},
            {"Angola", "AOA"},
            {"Anguilla", "XCD"},
            {"Antigua and Barbuda", "XCD"},
            {"Argentina", "ARS"},
            {"Armenia	East Europe", "AMD"},
            {"Aruba", "AWG"},
            {"Australia", "AUD"},
            {"Austria", "EUR"},
            {"Azerbaijan", "AZN"},
            {"Bahamas", "BSD"},
            {"Bahrain", "BHD"},
            {"Banglades", "BDT"},
            {"Barbados", "BBD"},
            {"Belarus", "BYR"},
            {"Belgium", "EUR"},
            {"Belize", "BZD"},
            {"Benin", "XOF"},
            {"Bermuda", "BMD"},
            {"Bhutan", "BTN"},
            {"Bolivia", "BOB"},
            {"Bosnia-Herzegovina", "BAM"},
            {"Botswana", "BWP"},
            {"Bouvet Island", "NOK"},
            {"Brazil", "BRL"},
            {"British Indian O. Terr", "GBP"},
            {"British Virgin Islands", "USD"},
            {"Brunei Darussalam ", "BND"},
            {"Bulgaria", "BGN"},
            {"Burkina Faso", "XOF"},
            {"Burundi", "BIF"},
            {"Cambodia", "KHR"},
            {"Cameroon", "XAF"},
            {"Canada", "CAD"},
            {"Cape Verde", "CVE"},
            {"Cayman Islands", "KYD"},
            {"Central African Rep", "XAF"},
            {"Chad", "XAF"},
            {"Chile", "CLP"},
            {"China", "CNY"},
            {"Christmas Island", "AUD"},
            {"Cocos", "AUD"},
            {"Colombia", "COP"},
            {"Comoros", "KMF"},
            {"Congo", "XAF"},
            {"Cook Islands", "NZD"},
            {"Costa Rica", "CRC"},
            {"Croatia", "HRK"},
            {"Cuba", "CUC"},
            {"Cyprus", "EUR"},
            {"Czech Republic", "CZK"},
            {"Democratic Republic of Congo", "CDF"},
            {"Denmark	Occidental", "DKK"},
            {"Djibouti", "DJF"},
            {"Dominica", "XCD"},
            {"Dominican Republic", "DOP"},
            {"Ecuador", "USD"},
            {"Egypt", "EGP"},
            {"El Salvador", "SVC"},
            {"Eritrea", "ERN"},
            {"Estonia", "EUR"},
            {"Ethiopia", "ETB"},
            {"European Union", "EUR"},
            {"Falkland Isl", "FKP"},
            {"Faroe Islands", "DKK"},
            {"Fiji", "FJD"},
            {"Finland", "EUR"},
            {"France", "EUR"},
            {"France", "EUR"},
            {"French Guiana", "EUR"},
            {"French Polynesia", "XPF"},
            {"French Southern Terr", "EUR"},
            {"Gabon", "XAF"},
            {"Gambia", "GMD"},
            {"Georgia", "GEL"},
            {"Germany", "EUR"},
            {"Ghana", "GHS"},
            {"Gibraltar", "GIP"},
            {"Great Britain", "GBP"},
            {"Greece", "EUR"},
            {"Greenland", "DKK"},
            {"Grenada", "XCD"},
            {"Guadaloupe", "EUR"},
            {"Guam", "USD"},
            {"Guatemala", "GTQ"},
            {"Guernsey", "GGP"},
            {"Guinea", "GNF"},
            {"Guinea Bissau", "XAF"},
            {"Guyana", "GYD"},
            {"Haiti", "HTG"},
            {"Heard and McDonald Isl", "AUD"},
            {"Honduras", "HNL"},
            {"Hong Kong", "HKD"},
            {"Hungary", "HUF"},
            {"Iceland", "ISK"},
            {"Indonesia", "IDR"},
            {"Iran", "IRR"},
            {"Iraq", "IQD"},
            {"Ireland", "EUR"},
            {"Isle of Man", "IMP"},
            {"Israel", "ILS"},
            {"Italy", "EUR"},
            {"Ivory Coast", "XOF"},
            {"Jamaica", "JMD"},
            {"Japan", "JPY"},
            {"Jersey", "JEP"},
            {"Jordan", "JOD"},
            {"Kazakhstan", "KZT"},
            {"Kenya", "KES"},
            {"Kiribati", "AUD"},
            {"Kuwait", "KWD"},
            {"Kyrgyz", "KGS"},
            {"Laos", "LAK"},
            {"Latvia", "EUR"},
            {"Lebanon", "LBP"},
            {"Lesotho", "LSL"},
            {"Liberia", "LRD"},
            {"Libya", "LYD"},
            {"Liechtenstein", "CHF"},
            {"Lithuania", "LTL"},
            {"Luxembourg ", "EUR"},
            {"Macau", "MOP"},
            {"Macedonia", "MKD"},
            {"Madagascar", "MGA"},
            {"Malawi", "MWK"},
            {"Malaysia", "MYR"},
            {"Maldives", "MVR"},
            {"Mali", "XOF"},
            {"Malta", "EUR"},
            {"Marshall Islands", "USD"},
            {"Martinique", "EUR"},
            {"Mauritania", "MRO"},
            {"Mauritius", "MUR"},
            {"Mayotte", "EUR"},
            {"Mexico", "MXN"},
            {"Micronesia", "USD"},
            {"Moldova", "MDL"},
            {"Monaco", "EUR"},
            {"Mongolia", "MNT"},
            {"Montenegro", "EUR"},
            {"Montserrat", "XCD"},
            {"Morocco", "MAD"},
            {"Mozambique", "MZN"},
            {"Myanmar", "MMK"},
            {"Namibia", "NAD"},
            {"Nauru", "AUD"},
            {"Nepal", "NPR"},
            {"Netherland", "ANG"},
            {"Netherlands", "EUR"},
            {"New Caledonia", "XPF"},
            {"New Zealand", "NZD"},
            {"Nicaragua", "NIO"},
            {"Niger", "XOF"},
            {"Nigeria", "NGN"},
            {"Niue", "NZD"},
            {"Norfolk Island", "AUD"},
            {"North Korea", "KPW"},
            {"Northern Mariana Isl", "USD"},
            {"Norway", "NOK"},
            {"Oman", "OMR"},
            {"Pakistan", "PKR"},
            {"Palau", "USD"},
            {"Palestine", "ILS"},
            {"Panama", "PAB"},
            {"Papua New Guinea", "PGK"},
            {"Paraguay", "PYG"},
            {"Peru", "PEN"},
            {"Philippines", "PHP"},
            {"Pitcairn", "NZD"},
            {"Poland", "PLN"},
            {"Portugal", "EUR"},
            {"Puerto Rico", "USD"},
            {"Qatar", "QAR"},
            {"Reunion", "EUR"},
            {"Romania", "RON"},
            {"Russian Federation", "RUB"},
            {"Rwanda", "RWF"},
            {"Saint Lucia", "XCD"},
            {"Saint Pierre and Miquelon", "EUR"},
            {"San Marino", "EUR"},
            {"Saudi Arabia", "SAR"},
            {"Senegal", "XOF"},
            {"Serbia", "RSD"},
            {"Seychelles", "SCR"},
            {"Sierra Leone", "SLL"},
            {"Singapore", "SGD"},
            {"Sint Maarten", "ANG"},
            {"Slovakia", "EUR"},
            {"Slovenia", "EUR"},
            {"Solomon Islands", "SBD"},
            {"Somalia", "SOS"},
            {"South Africa", "ZAR"},
            {"South Georgia and South Sandwich Islands", "GBP"},
            {"South Korea", "KRW"},
            {"South Sudan", "SSP"},
            {"Soviet Union", "RUB"},
            {"Spain", "EUR"},
            {"Sri Lanka", "LKR"},
            {"St. Helena", "SHP"},
            {"St. Tome and Principe", "STD"},
            {"St.Kitts Nevis Anguilla", "XCD"},
            {"St.Vincent and Grenadines", "XCD"},
            {"Sudan", "SDG"},
            {"Suriname", "SRD"},
            {"Svalbard and Jan Mayen Is", "NOK"},
            {"Swaziland", "SZL"},
            {"Sweden", "SEK"},
            {"Switzerland", "CHF"},
            {"Syria", "SYP"},
            {"Taiwan", "TWD"},
            {"Tajikistan", "TJS"},
            {"Tanzania", "TZS"},
            {"Thailand", "THB"},
            {"Timor-Leste", "USD"},
            {"Togo", "XOF"},
            {"Tokelau", "NZD"},
            {"Tonga", "TOP"},
            {"Trinidad and Tobago", "TTD"},
            {"Tunisia", "TND"},
            {"Turkey", "TRY"},
            {"Turkmenistan", "TMT"},
            {"Turks and Caicos Islands", "USD"},
            {"Tuvalu", "AUD"},
            {"Uganda", "UGX"},
            {"Ukraine", "UAH"},
            {"United Arab Emirates", "AED"},
            {"United States", "USD"},
            {"Uruguay", "UYU"},
            {"US Minor outlying Isl", "USD"},
            {"US Virgin Islands", "USD"},
            {"Uzbekistan", "UZS"},
            {"Vanuatu", "VUV"},
            {"Vatican City State", "EUR"},
            {"Venezuela", "VEF"},
            {"Vietnam", "VND"},
            {"Wallis and Futuna Islands", "XPF"},
            {"Western Sahara", "MAD"},
            {"Western Samoa", "WST"},
            {"Yemen", "YER"},
            {"Yugoslavia", "YUN"},
            {"Zambia", "ZMW"},
            {"Zimbabwe", "USD"}};

    String[][] dropdowncountryDetails = {
            {"India (+91)", "IN", "91"},
            {"Canada (+1)", "CA", "1"},
            {"United Kingdom (+44)", "GB", "44"},
            {"United States (+1)", "US", "1"},
            {"More", "", ""}
    };

    public String getCountryName(int index) {
        try {
            return countryDetails[index][0];
        } catch (Exception e) {
            e.printStackTrace();
            return "India";
        }
    }

    public String getCountryCode(int index) {
        try {
            return countryDetails[index][2];
        } catch (Exception e) {
            e.printStackTrace();
            return "91";
        }
    }

    public String getCountryAbrevation(int index) {
        try {
            return countryDetails[index][1];
        } catch (Exception e) {
            e.printStackTrace();
            return "IN";
        }
    }

    public String[] getCountriesList() {
        int length = countryDetails.length;
        String[] countryNames = new String[length];
        for (int i = 0; i < length; i++) {
            countryNames[i] = countryDetails[i][0];
        }
        return countryNames;
    }

    public String[] getCountryForCurrencyList() {
        int length = countryCurrency.length;
        String[] currency = new String[length];
        for (int i = 0; i < length; i++) {
            currency[i] = countryCurrency[i][0];
        }
        return currency;
    }

    public String[] getCurrencyForCountryList() {
        int length = countryCurrency.length;
        String[] currency = new String[length];
        for (int i = 0; i < length; i++) {
            currency[i] = countryCurrency[i][1];
        }
        return currency;
    }


    public String[] getDropDownCountriesList() {
        int length = dropdowncountryDetails.length;
        String[] countryNames = new String[length];
        for (int i = 0; i < length; i++) {
            countryNames[i] = dropdowncountryDetails[i][0];
        }
        return countryNames;
    }
}
